### ISSUE TITLE
Self-attention vs. MultiHeadAttention

### ISSUE THREAD

**Issue by DeepAlchemist** [PeizeSun/SparseR-CNN#4]
I am confused about the difference between Self-attention in table 4 and multi-head-attention in table 8.
Because in [this line](https://github.com/PeizeSun/SparseR-CNN/blob/64219dd447f0db8765297b666b1cf6e434cdd957/projects/SparseR-CNN/sparsercnn/head.py#L126), you assign multi-head-attention to self_attn.

![image](https://user-images.githubusercontent.com/50560933/100350626-22c21500-3025-11eb-9f7a-82ceaea6e8da.png)
![image](https://user-images.githubusercontent.com/50560933/100350656-2eadd700-3025-11eb-863c-3301a908f761.png)

**Comment by PeizeSun** [comment]
Hi~  
Maybe you could compare Sparse R-CNN and DETR:
In Sparse R-CNN, object recognition head is dynamic head,  dynamic head = **self-attention** + instance interaction（Table 4）; 
whereas, in DETR, object recognition head is decoder,  decoder = **self-attention** + **cross-attention**. 
The implementation of above **self-attention**, **self-attention**,**cross-attention** are all multi-head attention.

Since instance interaction could also be multi-head attention, we conduct experiments in Table 8 to compare.

**Comment by DeepAlchemist** [comment]
I get it. Thanks.
